apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  minReadySeconds: 30  # Ensure a pod is ready for at least 30 seconds
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: gcr.io/cogent-sign-431114-e4/fastapi-docker-ml:v1
        imagePullPolicy: Always  # Added imagePullPolicy
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"


